Update Move_issue_to_WitcherTPRG.yml

diff --git a/.github/workflows/Move_issue_to_WitcherTPRG.yml b/.github/workflows/Move_issue_to_WitcherTPRG.yml
--- a/.github/workflows/Move_issue_to_WitcherTPRG.yml
+++ b/.github/workflows/Move_issue_to_WitcherTPRG.yml
@@ -15,6 +15,8 @@ jobs:
           BOARD_ID: 1    # Замените на реальный ID доски "Backlog"
         run: |
           views=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/Pushkinmazila/projects/3/views/1" | jq)
-          
-          echo "Views in board 'Backlog' (project 'WitcherTPRG'):"
-          echo "$views"
+      - name: Check for errors
+        if: steps.get_views.outcome == 'failure'
+        run: |
+          echo "{{ failure-message }}"
+          exit 1
